# Generated by Django 4.0.5 on 2022-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mydata',
            name='BackEnd',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mydata',
            name='SlackUserName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
