# Generated by Django 4.0.5 on 2022-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_alter_mydata_age_alter_mydata_backend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='BackEnd',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='mydata',
            old_name='SlackUserName',
            new_name='slackUsername',
        ),
    ]
