# Generated by Django 4.0.5 on 2022-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_fetchmodel_rename_age_mydata_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='operation_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
