# Generated by Django 4.0.5 on 2022-11-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_alter_fetchmodel_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchmodel',
            name='operation_type',
            field=models.CharField(max_length=200),
        ),
    ]
